// lib/courses.ts
export interface Course {
    slug: string;
    title: string;
    description: string;
    duration: string;
    intake: string;
    fees: string;
    image: string;
    highlights: string[];
    category: "degree" | "diploma" | "advanced-diploma" | "short-term";
  }
  
  export const courses: Course[] = [
    {
      slug: "b-voc-in-multimedia-and-animation",
      title: "B.Voc. in Multimedia and Animation",
      description:
        "A 3-year undergraduate program offering multiple exit points in multimedia and animation, from diploma to full degree.",
      duration: "3 Years",
      intake: "60 Students",
      fees: "₹1,61,000 total",
      image: "https://subharti.bvocskill.com/img/courses/multimedia-animation.webp",
      highlights: [
        "Multiple exit options: Diploma, Advanced Diploma, Degree",
        "Hands-on training in multimedia and animation",
        "Industry partnership with Lingaya's Vidyapeeth",
        "State-of-the-art animation and VFX labs",
        "Industry-recognized certifications (Adobe, Autodesk)",
        "Located at BCM Campus, Ludhiana",
      ],
      category: "degree",
    },
    {
      slug: "graphic-designing-2d-and-3d",
      title: "Graphic Designing 2D and 3D",
      description: "A 1-year diploma covering comprehensive graphic design skills for 2D and 3D applications.",
      duration: "1 Year",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://rmskytech.com/wp-content/uploads/2024/08/graphic-designer-hd-image.jpg",
      highlights: [
        "2D and 3D design techniques",
        "Industry-standard tools (Adobe, Blender)",
        "Project-based learning",
        "Portfolio development",
        "Career support",
      ],
      category: "diploma",
    },
    {
      slug: "graphic-and-web-designing",
      title: "Graphic and Web Designing",
      description: "A 1-year diploma combining graphic design and web design skills for modern digital applications.",
      duration: "1 Year",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "Graphic design fundamentals",
        "Web design and development",
        "Responsive design principles",
        "Project-based learning",
        "Industry certifications",
      ],
      category: "diploma",
    },
    {
      slug: "motion-graphics-and-2d-animation",
      title: "Motion Graphics and 2D Animation",
      description: "A 1-year diploma focusing on animation and motion graphics skills for media and entertainment.",
      duration: "1 Year",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/8127803/pexels-photo-8127803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "2D animation techniques",
        "Motion graphics design",
        "Industry-standard tools (After Effects, Animate)",
        "Portfolio development",
        "Hands-on projects",
      ],
      category: "diploma",
    },
    {
      slug: "animation-and-vfx",
      title: "Animation and VFX",
      description: "A 1-year diploma combining animation and visual effects for film, gaming, and media industries.",
      duration: "1 Year",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_wUmoiOZzvdEH3UttbpYaZDOCo3y12219iA&s",
      highlights: [
        "Animation and VFX workflows",
        "3D modeling and compositing",
        "Industry-standard tools (Maya, Nuke)",
        "Capstone project",
        "Career support",
      ],
      category: "diploma",
    },
    {
      slug: "game-design-and-development",
      title: "Game Design and Development",
      description: "A 1-year diploma covering the complete game creation process, from concept to deployment.",
      duration: "1 Year",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://www.berlinsbi.com/uploads/sites/2/2024/01/Game-Design.jpg?w=1920&h=1080&crop=1",
      highlights: [
        "Game design fundamentals",
        "Game engine usage (Unity, Unreal)",
        "Level design and prototyping",
        "Portfolio development",
        "Industry exposure",
      ],
      category: "diploma",
    },
    {
      slug: "build-your-metaverse",
      title: "Build your Metaverse",
      description: "An 8-week intensive course on developing metaverse environments and applications.",
      duration: "8 Weeks",
      intake: "Open Enrollment",
      fees: "₹40,000",
      image: "https://images.pexels.com/photos/8721318/pexels-photo-8721318.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "Metaverse platform development",
        "3D environment creation",
        "Integration with AR/VR",
        "Hands-on projects",
        "Certification included",
      ],
      category: "diploma",
    },
    {
      slug: "multimedia-and-digital-marketing",
      title: "Multimedia and Digital Marketing",
      description: "A 1-year diploma combining multimedia skills with digital marketing strategies.",
      duration: "1 Year",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://online.hbs.edu/Style%20Library/api/resize.aspx?imgpath=/PublishingImages/blog/posts/digital-marketing-skills.jpg&w=1200&h=630",
      highlights: [
        "Multimedia content creation",
        "Digital marketing strategies",
        "Social media management",
        "Project-based learning",
        "Industry certifications",
      ],
      category: "diploma",
    },
    {
      slug: "complete-digital-marketing-with-ai",
      title: "Complete Digital Marketing with AI",
      description: "A 1-year diploma focusing on AI-enhanced digital marketing techniques.",
      duration: "1 Year",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://online.hbs.edu/Style%20Library/api/resize.aspx?imgpath=/PublishingImages/blog/posts/digital-marketing-skills.jpg&w=1200&h=630",
      highlights: [
        "AI-driven marketing strategies",
        "SEO and SEM techniques",
        "Data analytics for marketing",
        "Hands-on campaigns",
        "Certification included",
      ],
      category: "diploma",
    },
    {
      slug: "advanced-animation-and-vfx",
      title: "Advanced Animation and VFX",
      description: "A 2-year advanced diploma focusing on advanced techniques in animation and visual effects.",
      duration: "2 Years",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/8728556/pexels-photo-8728556.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "Advanced animation workflows",
        "VFX compositing and rendering",
        "Industry-standard tools (Houdini, Nuke)",
        "Portfolio development",
        "Industry internships",
      ],
      category: "advanced-diploma",
    },
    {
      slug: "advance-3d-animation",
      title: "Advance 3D Animation",
      description: "A 2-year advanced diploma specializing in 3D animation techniques for film and gaming.",
      duration: "2 Years",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/8728285/pexels-photo-8728285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "3D animation pipelines",
        "Character rigging and animation",
        "Motion capture techniques",
        "Capstone project",
        "Career support",
      ],
      category: "advanced-diploma",
    },
    {
      slug: "advance-visual-effects",
      title: "Advance Visual Effects",
      description: "A 2-year advanced diploma focusing on advanced visual effects techniques for media production.",
      duration: "2 Years",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/7749095/pexels-photo-7749095.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "Advanced VFX workflows",
        "Real-time rendering",
        "Compositing and simulation",
        "Portfolio development",
        "Industry exposure",
      ],
      category: "advanced-diploma",
    },
    {
      slug: "advanced-game-design-and-development",
      title: "Advanced Game Design and Development",
      description: "A 2-year advanced diploma equipping students with specialized skills in game creation and immersive gameplay design.",
      duration: "2 Years",
      intake: "40 Students",
      fees: "Contact for details",
      image: "https://www.berlinsbi.com/uploads/sites/2/2024/01/Game-Design.jpg?w=1920&h=1080&crop=1",
      highlights: [
        "End-to-end game development",
        "Advanced game engines (Unity, Unreal)",
        "Immersive UI/UX for gaming",
        "Portfolio development",
        "High-end gaming lab access",
      ],
      category: "advanced-diploma",
    },
    {
      slug: "graphic-design",
      title: "Graphic Design",
      description: "A 3-6 month course teaching basic design principles and tools for creating visual content.",
      duration: "3-6 Months",
      intake: "Open Enrollment",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/8728130/pexels-photo-8728130.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "Design principles and typography",
        "Adobe Photoshop and Illustrator",
        "Project-based learning",
        "Portfolio creation",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "2d-animation",
      title: "2D Animation",
      description: "A 3-6 month course providing a foundation in 2D animation techniques.",
      duration: "3-6 Months",
      intake: "Open Enrollment",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/8127803/pexels-photo-8127803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "2D animation fundamentals",
        "Storyboarding and animatics",
        "Adobe Animate and After Effects",
        "Hands-on projects",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "game-design",
      title: "Game Design",
      description: "A 3-6 month course covering the fundamentals of game design and development.",
      duration: "3-6 Months",
      intake: "Open Enrollment",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/6941872/pexels-photo-6941872.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "Game design principles",
        "Prototyping and level design",
        "Unity and Unreal Engine basics",
        "Portfolio development",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "ai-garage-for-professionals",
      title: "AI Garage for Professionals",
      description: "A 2-month course on AI applications tailored for working professionals.",
      duration: "2 Months",
      intake: "Open Enrollment",
      fees: "₹25,000",
      image: "https://images.pexels.com/photos/7749095/pexels-photo-7749095.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "AI tools and applications",
        "Machine learning basics",
        "Industry case studies",
        "Hands-on AI projects",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "introduction-to-ar-vr",
      title: "Introduction to AR/VR",
      description: "A 3-6 month course introducing the basics of augmented and virtual reality development.",
      duration: "3-6 Months",
      intake: "Open Enrollment",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/8721318/pexels-photo-8721318.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "AR/VR fundamentals",
        "Development tools (Unity, ARKit)",
        "Creating immersive experiences",
        "Hands-on projects",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "digital-marketing",
      title: "Digital Marketing",
      description: "A 3-6 month course covering digital marketing fundamentals and strategies.",
      duration: "3-6 Months",
      intake: "Open Enrollment",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/8962433/pexels-photo-8962433.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "SEO and SEM strategies",
        "Social media marketing",
        "Content marketing",
        "Analytics and reporting",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "web-development",
      title: "Web Development",
      description: "A 3-6 month course teaching the basics of web development and design.",
      duration: "3-6 Months",
      intake: "Open Enrollment",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "HTML, CSS, and JavaScript",
        "Responsive web design",
        "Frontend frameworks",
        "Hands-on projects",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "ui-ux-design",
      title: "UI/UX Design",
      description: "A 3-6 month course focusing on user interface and experience design principles.",
      duration: "3-6 Months",
      intake: "Open Enrollment",
      fees: "Contact for details",
      image: "https://images.pexels.com/photos/8728303/pexels-photo-8728303.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "UI/UX design principles",
        "Wireframing and prototyping",
        "User research and testing",
        "Design tools (Figma, Adobe XD)",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "basics-of-artificial-intelligence",
      title: "Basics of Artificial Intelligence",
      description: "An 8-week course introducing AI fundamentals and applications.",
      duration: "8 Weeks",
      intake: "Open Enrollment",
      fees: "₹25,000",
      image: "https://images.pexels.com/photos/7749095/pexels-photo-7749095.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "AI concepts and algorithms",
        "Machine learning basics",
        "AI tools and frameworks",
        "Hands-on projects",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "augmented-reality-and-virtual-reality",
      title: "Augmented Reality & Virtual Reality",
      description: "A 6-week course on AR/VR development skills for immersive applications.",
      duration: "6 Weeks",
      intake: "Open Enrollment",
      fees: "₹35,000",
      image: "https://images.pexels.com/photos/8721318/pexels-photo-8721318.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "AR/VR development tools",
        "Creating immersive experiences",
        "Unity and ARKit/ARCore",
        "Hands-on projects",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "ai-animation-and-digital-twin",
      title: "AI Animation & Digital Twin",
      description: "A 3-month course focusing on AI-powered animation and digital twin creation.",
      duration: "3 Months",
      intake: "Open Enrollment",
      fees: "₹60,000",
      image: "https://images.pexels.com/photos/7749095/pexels-photo-7749095.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "AI integration in animation",
        "Digital twin modeling",
        "Emerging AI design tools",
        "Project-based delivery",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "introduction-to-data-science",
      title: "Introduction to Data Science",
      description: "A 4-week course introducing data science fundamentals and techniques.",
      duration: "4 Weeks",
      intake: "Open Enrollment",
      fees: "₹30,000",
      image: "https://images.pexels.com/photos/8728760/pexels-photo-8728760.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "Data analysis and visualization",
        "Python for data science",
        "Statistical methods",
        "Hands-on projects",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "graphic-designing-still-motion-and-3d",
      title: "Graphic Designing (Still, Motion & 3D)",
      description: "A 3-month course covering comprehensive graphic design skills.",
      duration: "3 Months",
      intake: "Open Enrollment",
      fees: "₹50,000",
      image: "https://images.pexels.com/photos/8728130/pexels-photo-8728130.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "Still, motion, and 3D design",
        "Adobe Creative Suite",
        "Project-based learning",
        "Portfolio creation",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "visual-effects-vfx",
      title: "Visual Effects (VFX)",
      description: "A 4-month course on VFX creation techniques for film and media.",
      duration: "4 Months",
      intake: "Open Enrollment",
      fees: "₹55,000",
      image: "https://images.pexels.com/photos/8728285/pexels-photo-8728285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "VFX compositing and rendering",
        "Industry-standard tools (Nuke, Houdini)",
        "Motion tracking and rotoscoping",
        "Hands-on projects",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "animation",
      title: "Animation",
      description: "A 6-month course covering animation principles and techniques.",
      duration: "6 Months",
      intake: "Open Enrollment",
      fees: "₹70,000",
      image: "https://images.pexels.com/photos/7915487/pexels-photo-7915487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "2D and 3D animation",
        "Character animation",
        "Storyboarding and animatics",
        "Portfolio development",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "game-design-and-development-short-term",
      title: "Game Design & Development",
      description: "A 6-month course on the game design and development process.",
      duration: "6 Months",
      intake: "Open Enrollment",
      fees: "₹65,000",
      image: "https://images.pexels.com/photos/6941872/pexels-photo-6941872.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "Game design and mechanics",
        "Game engines (Unity, Unreal)",
        "Level design and prototyping",
        "Portfolio development",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "digital-marketing-and-data-analytics",
      title: "Digital Marketing & Data Analytics",
      description: "A 3-month course on digital marketing with a focus on data analytics.",
      duration: "3 Months",
      intake: "Open Enrollment",
      fees: "₹40,000",
      image: "https://images.pexels.com/photos/8962433/pexels-photo-8962433.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "Digital marketing strategies",
        "Data analytics for marketing",
        "SEO and SEM techniques",
        "Hands-on campaigns",
        "Certification included",
      ],
      category: "short-term",
    },
    {
      slug: "web-design-and-development",
      title: "Web Design & Development",
      description: "A 3-month course on web creation and development techniques.",
      duration: "3 Months",
      intake: "Open Enrollment",
      fees: "₹45,000",
      image: "https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      highlights: [
        "HTML, CSS, and JavaScript",
        "Responsive web design",
        "Frontend frameworks",
        "Hands-on projects",
        "Certification included",
      ],
      category: "short-term",
    },
  ];